org.gradle.java.installations.paths=E:\\JavaEnvironmentVariables\\jdk-8,E:\\JavaEnvironmentVariables\\jdk-11,E:\\JavaEnvironmentVariables\\jdk-17,E:\\JavaEnvironmentVariables\\jdk-21,E:\\JavaEnvironmentVariables\\jdk-25,E:\\JavaEnvironmentVariables\\jdk-26
org.gradle.java.installations.auto-detect=true
